ignore:
  - "E501"  # Игнорировать ошибку длины строки более 80 символов (вы можете использовать соответствующий код ошибки)
  - "S101"  # Игнорировать отсутствие assert или fail в тестовых методах
  - "WPS323"  # Игнорировать ошибку разделения строк Private final
