spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:education}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:education}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  properties:
    hibernate:
    format_sql: true
app:
  security:
    refreshTokenDurationMs: 600000000
    jwtSecret: "======================Education=Spring==========================="
    jwtExpirationMs: 600000000
    jwtCookie: "education-jwt"
    jwtRefreshCookie: "education-jwt-refresh"