package com.example.educationapp.controlleradvice;

public enum Errors {
    COURSE_NAME_TAKEN, STATUS_IS_INVALID, USERNAME_TAKEN, EMAIL_TAKEN, BAD_CREDITIANS,
    LESSON_NAME_TAKEN, HW_ALREADY_EXISTS, HWD_ALREADY_EXISTS, STUDENT_ALREADY_EXISTS,
    TEACHER_ALREADY_EXISTS, AUTHOR_ALREADY_EXISTS, HW_DONE_IS_NOT_FOUND
}
