minio:
  bucket: "education"
  client:
    endpoint: "https://194.87.190.26:9000"
    accessKey: "admin"
    secretKey: "7D3ffTPfo0h705Nn"
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:194.87.190.26}:${DATABASE_PORT:5432}/${DATABASE_NAME:education}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:education}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  properties:
    hibernate:
    format_sql: true
app:
  security:
    refreshTokenDurationMs: 600000000
    jwtSecret: "======================Education=Spring==========================="
    jwtExpirationMs: 1800000
    jwtCookie: "education-jwt"
    jwtRefreshCookie: "education-jwt-refresh"
springdoc:
  api-docs:
    enabled: true
    path: /swagger-config/education/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
