spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:education}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:education}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  properties:
    hibernate:
    format_sql: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:500MB}
      max-request-size: ${MAX_REQUEST_SIZE:500MB}
app:
  security:
    refreshTokenDurationMs: 600000000
    jwtSecret: "======================Education=Spring==========================="
    jwtExpirationMs: 1800000
    jwtCookie: "education-jwt"
    jwtRefreshCookie: "education-jwt-refresh"
springdoc:
  api-docs:
    enabled: true
    path: /swagger-config/education/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
