name: Pull request changed build

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'education-back/**'
  push:
    branches:
      - master
    paths:
      - 'education-back/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.output-data.outputs.image-url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Run chmod to make gradlew executable
        run: chmod +x ./education-back/gradlew

      - name: Build with Gradle
        run: ./education-back/gradlew build
