name: build-front

on:
  push:
    branches:
      - master
    paths:
      - 'education-front/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          cd education-front
          npm install
          CI=false npm run build
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH }}

      - name: Upload Frontend Build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH }}
          source: "./education-front/build"
          target: "/root/educationapp/"
